[features]
seeds = false
skip-lint = false
[programs.localnet]
messagefi_program = "DMyQ8keGbLzXNyqhRx8j6X4SDyB3EXG1ea94CfTu6tfR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
